[project]
name = "phone-py"
version = "0.0.0"

[build-system]
requires = ["maturin==1.8.7"]
build-backend = "maturin"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "Cargo.toml" }, { file = "src/*.rs" }]

[tool.maturin]
features = ["pyo3/extension-module"]
