[project]
name = "phone-py"
dynamic = ["version"]

[build-system]
requires = ["maturin-with-stub"]
build-backend = "maturin_with_stub"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "Cargo.toml" }, { file = "src/*.rs" }]

[tool.maturin]
features = ["pyo3/extension-module"]
