[package]
name = "cli"
version = "0.3.0"
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
cpal.workspace = true
crossbeam.workspace = true
dasp = { workspace = true, features = ["signal"] }
iroh.workspace = true
rancor.workspace = true
rand.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[build-dependencies]
bindgen.workspace = true
